### ISSUE TITLE
redirects from strangled source can break in 0.3.1

### ISSUE THREAD

**Issue by syphar** [MidasLamb/axum-strangler#4]
I was investigating using this library to help with migrating an old iron webserver to axum. 

The iron app creates redirects with the full path, and uses the `Host` header from the request to create the redirect URL. I saw this approach in many other apps, so it's not unique. 

Since 1645a36b2a488c657317d79f9eefdf8ffee2645c the Host-header is overwritten using the strangled authority host: https://github.com/MidasLamb/axum-strangler/blob/1645a36b2a488c657317d79f9eefdf8ffee2645c/src/lib.rs#L150-L154 

which breaks this, since the redirect is generated using the strangled hostname, not the original hostname. 

Was this an intentional change?

**Comment by MidasLamb** [comment]
This was indeed an intentional change, reason being that sometimes there could be other proxies in between that use the hostname to forward the request to the strangled service. The one where I experienced this was that the strangled service was in a k8s cluster with traefik as ingress. Without this rewriting, the strangled service couldn't be reached.

However, the fact that it was intentional does not mean that your usecase shouldn't be supported. I see some possible avenues:
* Make the request host rewriting configurable
* Overwrite the host in a redirect response, if it matches the strangled host

It's probably best to make the request host rewriting configurable regardless of this specific issue, however what are your thoughts on the redirect response host rewriting?

**Comment by MidasLamb** [comment]
Should be fixed by #13

**Comment by syphar** [comment]
#13 looks like it will solve this :) 

Thank you!

**Comment by MidasLamb** [comment]
@syphar , I've published a release candidate for v0.4.0: https://crates.io/crates/axum-strangler/0.4.0-rc.1
